version: '3'
services:
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /docker-entrypoint-initdb.d/postgres_password
    volumes:
    - generated:/docker-entrypoint-initdb.d
    - shared:/shared
    command:
      - -c
      - "listen_addresses=*"
  db_setup:
    image: selene-backend
    restart: "on-failure"
    depends_on:
      - db
    links:
      - db
    volumes:
    - shared:/shared
    command:
      - bash
      - -c
      - "set -xe && sleep 10 && cd /opt/selene/selene-backend/db/scripts && pipenv run python -u bootstrap_mycroft_db.py && touch /shared/db_bootstrap_done"
      # TODO: Get rid of the sleep above. Open a PR to make the bootstrap script to retry if it fails to connect
      # The postgres image restart itself after running init scripts and this script looses the connection
      # and can't recover.
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_HOST: "db"
  redis:
    image: redis:5.0.7
    restart: always
  sso:
    image: selene-backend
    restart: "on-failure"
    volumes:
    - shared:/shared
    links:
      - db
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/sso && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      GITHUB_CLIENT_ID: <github client id> TODO
      GITHUB_CLIENT_SECRET: <github client secret> TODO
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      JWT_RESET_SECRET: "${JWT_RESET_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      SENDGRID_API_KEY: <sendgrid API key> TODO
      SSO_BASE_URL: "${SSO_BASE_URL}"
  account:
    image: selene-backend
    restart: "on-failure"
    volumes:
    - shared:/shared
    links:
      - db
      - redis
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/account && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH_BASE_URL: "${OAUTH_BASE_URL}"
  skills_setup:
    image: selene-backend
    restart: "on-failure"
    volumes:
    - shared:/shared
    links:
      - db
      - redis
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/batch && /usr/local/bin/pipenv install &&  pipenv run python script/load_skill_display_data.py --core-version 19.08 && touch /shared/skills_setup_done
        "
        # TODO: core-version shouldn't be hardcoded (get latest somehow?)
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      GITHUB_USER: "${GITHUB_USER}"
      GITHUB_PASSWORD: "${GITHUB_PASSWORD}"
  market:
    image: selene-backend
    restart: "on-failure"
    volumes:
    - shared:/shared
    links:
      - db
      - redis
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/skills_setup_done ]; then echo 'Skills downloading and setup not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/market && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH_BASE_URL: "${OAUTH_BASE_URL}"
  devices:
    image: selene-backend
    restart: "on-failure"
    volumes:
    - shared:/shared
    links:
      - db
      - redis
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/skills_setup_done ]; then echo 'Skills downloading and setup not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/public && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH_BASE_URL: "${OAUTH_BASE_URL}"
      SELENE_ENVIRONMENT: prod
      SALT: "${ENCRYPTION_SALT}"
      EMAIL_SERVICE_HOST: "${EMAIL_SERVICE_HOST}"
      EMAIL_SERVICE_PORT: "${EMAIL_SERVICE_PORT}"
      EMAIL_SERVICE_USER: "${EMAIL_SERVICE_USER}"
      EMAIL_SERVICE_PASSWORD: "${EMAIL_SERVICE_PASSWORD}"
      GOOGLE_STT_KEY: "${GOOGLE_STT_KEY}" # NOTE: Optional if you plan to use Google for STT
      OWM_KEY: "${OWM_KEY}"
      OWM_URL: "https://api.openweathermap.org/data/2.5"
      WOLFRAM_ALPHA_KEY: "${WOLFRAM_ALPHA_KEY}"
      WOLFRAM_ALPHA_URL: "https://api.wolframalpha.com"
  deepspeech:
    image: deepspeech
    restart: "on-failure"
    expose:
      - "8080"
  #mycroft:
  #  image: mycroftai/docker-mycroft
  #  restart: "on-failure"
  #  volumes:
  #    - mycroft_storage_dir:/root/.mycroft
  #    - pulse_runtime:${XDG_RUNTIME_DIR}/pulse/
  #    - pulse_config:/root/.config/pulse/
  #  environment:
  #    PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
   # ports:
  #    - "8181:8181"
 #   devices:
#      - "/dev/snd:/dev/snd"
  selene-ui-market:
    image: selene-ui-market
    restart: "on-failure"
  selene-ui-account:
    image: selene-ui-account
    restart: "on-failure"
  selene-ui-sso:
    image: selene-ui-sso
    restart: "on-failure"
  # This is and nginx reverse proxy that redirects all subdomains and api
  # endpoints to the correct container.
  selene-ui-proxy:
    image: mycroft-nginx-proxy
    restart: "on-failure"
    links:
      - market
      - sso
      - account
      - devices
      - selene-ui-market
      - selene-ui-sso
    depends_on:
      - market
      - sso
      - account
      - devices
      - selene-ui-market
      - selene-ui-sso
    ports:
      - "80:80"
      - "443:443"
volumes:
  generated:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/generated"
      o: bind
  mycroft_storage_dir:
    driver: local
    driver_opts:
      type: none
      device: "${MYCROFT_STORAGE_DIR}"
      o: bind
  pulse_runtime:
    driver: local
    driver_opts:
      type: none
      device: ${XDG_RUNTIME_DIR}/pulse/
      o: bind
  pulse_config:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/.config/pulse/
      o: bind
  shared:
